Adds new metadata values
cloud-bulldozer/go-commons pull request #40
Opened 2023-12-04 15:46 UTC by chentex

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

- Includes FIPS, Publish, and Architecture extraction

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

2023-12-04 15:53 UTC, jtaleric commented
Curious, what is Publish?

2023-12-05 08:58 UTC, chentex commented
> Curious, what is Publish?

It tells you if the cluster is External or Private facing, I ma open to new names

2023-12-05 09:19 UTC, rsevilla87 commented on ocp-metadata/types.go
> +	WorkerArch       string `json:"wrkerArch"`
typo?

2024-02-22 10:46 UTC, rsevilla87 reviewed
Remove d

2024-02-27 20:06 UTC, vishnuchalla commented
> > Curious, what is Publish?
> 
> It tells you if the cluster is External or Private facing, I'm open to new names

if its just a bool, can we rename it as `isPublic` or something?

2024-02-28 12:09 UTC, rsevilla87 commented on ocp-metadata/ocp-metadata.go
> +	installConfig, err := meta.getClusterConfig()
You're calling getClusterConfig many times along the different methods, I wonder if we can call this function only once

2024-02-28 12:16 UTC, rsevilla87 requested changes
The current metadata implementation doesn't crash when used on vanilla kubernetes clusters (kind), I wonder if it's possible to follow this strategy with the new fields.

For example, the library was handling the error of the infra object in these lines:


https://github.com/cloud-bulldozer/go-commons/blob/0140b108fb4b1723c1a94330acfdd7392efa2a7e/ocp-metadata/ocp-metadata.go#L173-L178

2024-03-04 15:02 UTC, chentex commented
Resolved all the comments.

2024-03-14 11:46 UTC, rsevilla87 approved these changes
lgtm,
works in OCP and Vanillla k8s

Vanilla k8s
```shell
$ go run main.go  | jq .
{
  "k8sVersion": "v1.29.2",
  "masterNodesCount": 1,
  "totalNodes": 1
}
```

OCP 4 .12
```shell
$ go run main.go  | jq .
{
  "platform": "AWS",
  "clusterType": "self-managed",
  "ocpVersion": "4.14.3",
  "ocpMajorVersion": "4.14",
  "k8sVersion": "v1.27.6+b49f9d1",
  "masterNodesType": "m6i.2xlarge",
  "masterNodesCount": 3,
  "workerNodesCount": 3,
  "totalNodes": 3,
  "sdnType": "OVNKubernetes",
  "clusterName": "ocp-ci-hq68v",
  "region": "us-west-2",
  "publish": "External",
  "workerArch": "amd64",
  "controlPlaneArch": "amd64",
  "ipsecMode": "Disabled"
}

```

2024-03-16 01:58 UTC, vishnuchalla approved these changes

2024-03-17 08:34 UTC, merged